### ISSUE TITLE
Look into what editor we can use

### ISSUE THREAD

**Issue by joehoyle** [joehoyle/vienna#4]
For the edit post content etc

**Comment by joehoyle** [comment]
@rmccue any update on the editors you were looking at getting building here?

**Comment by roundhill** [comment]
It'd be interesting to try out `drafts-js` for this app: https://facebook.github.io/draft-js/

**Comment by rmccue** [comment]
The new [Aztec editor](https://make.wordpress.org/mobile/2017/04/08/introducing-the-aztec-mobile-editors/) looks pretty good. Previous work here stalled because the existing editors require a ViewController, which would have required us to use [react-native-controllers](https://github.com/wix/react-native-controllers), a pretty big dependency. The new Aztec editor is just a view, so should be easier to integrate.

**Comment by joehoyle** [comment]
Looks like we're moving ahead with Aztec here, so closing out.
